export const plans = [
  {
    id: "1",
    name: "Basic",
    price: 49,
    duration: "Weekly",
    description: "Perfect for beginners starting their fitness journey",
    features: [
      "Access to gym equipment",
      "Locker room access",
      "Free fitness assessment",
      "Mobile app access",
    ],
    activeMembers: 342,
    isPopular: false,
  },
  {
    id: "2",
    name: "Premium",
    price: 99,
    duration: "Fortnightly",
    description: "Our most popular plan with unlimited access",
    features: [
      "All Basic features",
      "Unlimited group classes",
      "Free guest passes (2/month)",
      "Nutrition consultation",
      "Priority booking",
    ],
    activeMembers: 567,
    isPopular: true,
  },
  {
    id: "3",
    name: "Annual",
    price: 999,
    duration: "Yearly",
    description: "Best value with 2 months free",
    features: [
      "All Premium features",
      "2 months free",
      "Free personal training session",
      "Exclusive member events",
      "Towel service",
    ],
    activeMembers: 189,
    isPopular: false,
  },
  {
    id: "4",
    name: "Personal Training",
    price: 149,
    duration: "Monthly",
    description: "One-on-one coaching for serious results",
    features: [
      "All Premium features",
      "4 personal training sessions/month",
      "Customized workout plan",
      "Weekly progress tracking",
      "Meal planning guidance",
    ],
    activeMembers: 94,
    isPopular: false,
  },
]
